import csv
import re

raw_data = """
001 FACTURAS A
002 NOTAS DE DEBITO A
003 NOTAS DE CREDITO A
004 RECIBOS A
005 NOTAS DE VENTA AL CONTADO A
006 FACTURAS B
007 NOTAS DE DEBITO B
008 NOTAS DE CREDITO B
009 RECIBOS B
010 NOTAS DE VENTA AL CONTADO B
011 FACTURAS C
012 NOTAS DE DEBITO C 
013 NOTAS DE CREDITO C
015 RECIBOS C
016 NOTAS DE VENTA AL CONTADO C
017 LIQUIDACION DE SERVICIOS PUBLICOS CLASE A
018 LIQUIDACION DE SERVICIOS PUBLICOS CLASE B
019 FACTURAS DE EXPORTACION
020 NOTAS DE DEBITO POR OPERACIONES CON EL EXTERIOR
021 NOTAS DE CREDITO POR OPERACIONES CON EL EXTERIOR
022 FACTURAS - PERMISO EXPORTACION SIMPLIFICADO - DTO. 855/97
023 COMPROBANTES “A” DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO
024 COMPROBANTES “A” DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO
025 COMPROBANTES “B” DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO
026 COMPROBANTES “B” DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO
027 LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A
028 LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B
029 LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C
030 COMPROBANTES DE COMPRA DE BIENES USADOS
032 COMPROBANTES PARA RECICLAR MATERIALES
033 LIQUIDACION PRIMARIA DE GRANOS
034 COMPROBANTES A DEL APARTADO A INCISO F R G N 1415
035 COMPROBANTES B DEL ANEXO I, APARTADO A, INC.F), RG N° 1415
036 COMPROBANTES C DEL ANEXO I, APARTADO A, INC.F), R.G. N° 1415
037 NOTAS DE DEBITO O DOCUMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415
038 NOTAS DE CREDITO O DOCUMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415
039 OTROS COMPROBANTES A QUE CUMPLEN CON LA R G 1415
040 OTROS COMPROBANTES B QUE CUMPLAN CON LA R.G. 1415
041 OTROS COMPROBANTES C QUE CUMPLAN CON LA R.G. 1415
043 NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B
044 NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C 
045 NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A
046 NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B
047 NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C
048 NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A
049 COMPROBANTES DE COMPRA DE BIENES NO REGISTRABLES A CONSUMIDORES FINALES
050 RECIBO FACTURA A REGIMEN DE FACTURA DE CREDITO
051 FACTURAS M
052 NOTAS DE DEBITO M
053 NOTAS DE CREDITO M
054 RECIBOS M
055 NOTAS DE VENTA AL CONTADO M
056 COMPROBANTES M DEL ANEXO I APARTADO A INC F R G N 1415
057 OTROS COMPROBANTES M QUE CUMPLAN CON LA R G N 1415
058 CUENTAS DE VENTA Y LIQUIDO PRODUCTO M
059 LIQUIDACIONES M
060 CUENTAS DE VENTA Y LIQUIDO PRODUCTO A
061 CUENTAS DE VENTA Y LIQUIDO PRODUCTO B
063 LIQUIDACIONES A
064 LIQUIDACIONES B
066 DESPACHO DE IMPORTACION
068 LIQUIDACION C
070 RECIBOS FACTURA DE CREDITO
081 TIQUE FACTURA A CONTROLADORES FISCALES
082 TIQUE - FACTURA B
083 TIQUE
090 NOTA DE CREDITO OTROS COMP QUE NO CUMPLEN CON LA R G 1415 Y SUS MODIF
099 OTROS COMP QUE NO CUMPLEN CON LA R G 1415 Y SUS MODIF
109 TIQUE C
110 TIQUE NOTA DE CREDITO
111 TIQUE FACTURA C
112 TIQUE NOTA DE CREDITO A
113 TIQUE NOTA DE CREDITO B
114 TIQUE NOTA DE CREDITO C
115 TIQUE NOTA DE DEBITO A
116 TIQUE NOTA DE DEBITO B
117 TIQUE NOTA DE DEBITO C 
118 TIQUE FACTURA M
119 TIQUE NOTA DE CREDITO M
120 TIQUE NOTA DE DEBITO M
150 LIQUIDACION DE COMPRA PRIMARIA PARA EL SECTOR TABACALERO A
151 LIQUIDACION DE COMPRA PRIMARIA PARA EL SECTOR TABACALERO B
157 CUENTA DE VENTA Y LÍQUIDO PRODUCTO A – SECTOR AVÍCOLA
158 CUENTA DE VENTA Y LÍQUIDO PRODUCTO B – SECTOR AVÍCOLA
159 LIQUIDACIÓN DE COMPRA A – SECTOR AVÍCOLA
160 LIQUIDACIÓN DE COMPRA B – SECTOR AVÍCOLA
161 LIQUIDACIÓN DE COMPRA DIRECTA A - SECTOR AVÍCOLA
162 LIQUIDACIÓN DE COMPRA DIRECTA B - SECTOR AVÍCOLA
163 LIQUIDACIÓN DE COMPRA DIRECTA C - SECTOR AVÍCOLA
164 LIQUIDACIÓN DE VENTA DIRECTA A - SECTOR AVÍCOLA
165 LIQUIDACIÓN DE VENTA DIRECTA B - SECTOR AVÍCOLA
166 LIQUIDACIÓN DE CONTRATACIÓN DE CRIANZA POLLOS PARRILLEROS A
167 LIQUIDACIÓN DE CONTRATACIÓN DE CRIANZA POLLOS PARRILLEROS B
168 LIQUIDACIÓN DE CONTRATACIÓN DE CRIANZA POLLOS PARRILLEROS C
169 LIQUIDACIÓN DE CRIANZA POLLOS PARRILLEROS A
170 LIQUIDACIÓN DE CRIANZA POLLOS PARRILLEROS B
171 LIQUIDACIÓN DE COMPRA DE CAÑA DE AZÚCAR A
172 LIQUIDACIÓN DE COMPRA DE CAÑA DE AZÚCAR B
180 CUENTA DE VENTA Y LÍQUIDO PRODUCTO A - SECTOR PECUARIO
182 CUENTA DE VENTA Y LÍQUIDO PRODUCTO B - SECTOR PECUARIO
183 LIQUIDACIÓN DE COMPRA A - SECTOR PECUARIO
185 LIQUIDACIÓN DE COMPRA B - SECTOR PECUARIO
186 LIQUIDACIÓN DE COMPRA DIRECTA A - SECTOR PECUARIO
188 LIQUIDACIÓN DE COMPRA DIRECTA B - SECTOR PECUARIO
189 LIQUIDACIÓN DE COMPRA DIRECTA C - SECTOR PECUARIO
190 LIQUIDACIÓN DE VENTA DIRECTA A - SECTOR PECUARIO
191 LIQUIDACIÓN DE VENTA DIRECTA B - SECTOR PECUARIO 
195 FACTURA CLASE “T”
196 NOTA DE DÉBITO CLASE “T”
197 NOTA DE CRÉDITO CLASE “T”
201 FACTURA DE CRÉDITO ELECTRÓNICA MIPYMES (FCE) A
202 NOTA DE DÉBITO ELECTRÓNICA MIPYMES (FCE) A
203 NOTA DE CRÉDITO ELECTRÓNICA MIPYMES (FCE) A
206 FACTURA DE CRÉDITO ELECTRÓNICA MIPYMES (FCE) B
207 NOTA DE DÉBITO ELECTRÓNICA MIPYMES (FCE) B
208 NOTA DE CRÉDITO ELECTRÓNICA MIPYMES (FCE) B
211 FACTURA DE CRÉDITO ELECTRÓNICA MIPYMES (FCE) C
212 NOTA DE DÉBITO ELECTRÓNICA MIPYMES (FCE) C
213 NOTA DE CRÉDITO ELECTRÓNICA MIPYMES (FCE) C
331 LIQUIDACION SECUNDARIA DE GRANOS
332 CERTIFICACION ELECTRONICA (GRANOS) 
"""

rows = []
for line in raw_data.strip().split('\n'):
    line = line.strip()
    if not line: continue
    codigo = line[:3]
    nombre = line[4:].strip()

    # Letra inference
    letra = 'X'
    if re.search(r'\bA\b', nombre) or "CLASE A" in nombre or "“A”" in nombre or " A " in nombre: letra = 'A'
    if re.search(r'\bB\b', nombre) or "CLASE B" in nombre or "“B”" in nombre or " B " in nombre: letra = 'B'
    if re.search(r'\bC\b', nombre) or "CLASE C" in nombre or " C " in nombre: letra = 'C'
    if re.search(r'\bM\b', nombre) or "CLASE M" in nombre or " M " in nombre: letra = 'M'
    if re.search(r'\bT\b', nombre) or "CLASE “T”" in nombre: letra = 'T'
    if "EXPORTACION" in nombre or "EXTERIOR" in nombre: letra = 'E'

    if nombre.endswith(" A"): letra = "A"
    if nombre.endswith(" B"): letra = "B"
    if nombre.endswith(" C"): letra = "C"
    if nombre.endswith(" M"): letra = "M"

    # Clasificacion
    clasificacion = 'factura'
    if "NOTA DE DEBITO" in nombre or "NOTAS DE DEBITO" in nombre:
        clasificacion = 'nota_debito'
    elif "NOTA DE CREDITO" in nombre or "NOTAS DE CREDITO" in nombre:
        clasificacion = 'nota_credito'
    elif "RECIBO" in nombre or "RECIBOS" in nombre:
        clasificacion = 'recibo'
    elif "REMITO" in nombre or "DESPACHO" in nombre:
        clasificacion = 'remito'

    # Flags
    es_mipyme = 'True' if 'MIPYME' in nombre or 'FCE' in nombre else 'False'
    es_exportacion = 'True' if 'EXPORTACION' in nombre or 'EXTERIOR' in nombre else 'False'
    es_electronico = 'True'

    rows.append([codigo, nombre, letra, clasificacion, es_electronico, es_mipyme, es_exportacion])

with open('utils/tipos_comprobantes_afip.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['codigo','nombre','letra','clasificacion_interna','es_electronico','es_mipyme_fce','es_exportacion'])
    writer.writerows(rows)
