[project]
name = "indinopy"
version = "0.1.0"
author =  "Gabriel Sarthou"
description = "Mi proyecto de Django"
dependencies = [
    "afip-py>=1.2.0",
    "django>=6.1.1",
    "django-simple-history>=3.13.0",
    "psycopg2-binary>=2.9.13",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "requests>=2.31.0",
]

# 2. CONFIGURACIÓN GENERAL DE RUFF
[tool.ruff]
extend-exclude = ["*/migrations/*", ".venv", "venv"]
line-length = 88 

[tool.ruff.lint]
select = ["E", "F", "DJ", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
