[project]
name = "indinopy"
version = "0.1.0"
author =  "Gabriel Sarthou"
description = "Mi proyecto de Django"
dependencies = [
    "django",
    "django-simple-history>=3.13.0",
    "python-dotenv>=1.2.3",
]

# 2. CONFIGURACIÓN GENERAL DE RUFF
[tool.ruff]
extend-exclude = ["*/migrations/*", ".venv", "venv"]
line-length = 88 

[tool.ruff.lint]
select = ["E", "F", "DJ", "I"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
